variable "resource_group_location" {}
variable "resource_group_name" {}
variable "tags" {}
variable "resource_prefix" {}
variable "vnet_address_space" {}
variable "subnet_address_prefix" {}
variable "cluster_name" {}
variable "vnet_name" {}
variable "subnet_name" {}
variable "node_pool_name" {}
variable "vm_size" {}
variable "agent_count" {}
variable "log_analytics_workspace_name" {}
variable "log_analytics_workspace_location" {}
variable "log_analytics_workspace_sku" {}
variable "keyvault_rg" {}
variable "keyvault_name" {}
variable "keyvault_secret" {}
variable "client_id" {}
variable "enable_auto_scale" {}
variable "max_node_count" {}
variable "min_node_count" {}
variable "network_plugin" {}
variable "dashboard_enabled" {}
variable "oms_agent_enabled" {}
variable "rbac_enabled" {}