variable "location" {}
variable "resource_group_name" {}
variable "tags" {}
variable "cluster_name" {}
variable "resource_prefix" {}
variable "depends-on" {}
variable "node_pool_name" {}
variable "agent_count" {}
variable "vm_size" {}
variable "enable_auto_scale" {}
variable "max_node_count" {}
variable "min_node_count" {}
variable "subnet_id" {}
variable "service_principal_client_id" {}
variable "service_principal_client_secret" {}
variable "network_plugin" {}
variable "dashboard_enabled" {}
variable "oms_agent_enabled" {}
variable "log_analytics_workspace_id" {}
variable "role_based_access_control_enabled" {}